### GET
GET http://localhost:3000/api/Mudi


### DELETE
DELETE http://localhost:3000/api/employees/444


### POST
POST http://localhost:3000/api/employees
Content-Type: application/json

{
      "id": "444",
      "firstName": "Mudi",
      "lastName": "R"
}


### PATCH 
PATCH http://localhost:3000/api/employees/444
Content-Type: application/json

{
      "lastName": "Boris",
      "id": "123"

}

